on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 15.x
              distribution: zulu
        - run: |
              keytool -genkey -keystore release.jks -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -alias release -dname 'CN=(名字与姓氏), OU=(组织单位名称), O=(组织名称), L=(城市或区域名称), ST=(州或省份名称), C=(单位的两字母国家代码)'
              mkdir res
              $ANDROID_HOME/build-tools/32.0.0/aapt2 compile --dir res -o out.zip
              $ANDROID_HOME/build-tools/32.0.0/aapt2 link out.zip -I $ANDROID_HOME/platforms/android-32/android.jar --manifest AndroidManifest.xml -o out.apk
              gradle --warning-mode all copyDependencies
              javac -Xlint:deprecation -cp $ANDROID_HOME/platforms/android-32/android.jar:copyDependencies/*:. com/main/*.java
              $ANDROID_HOME/build-tools/32.0.0/d8 com/main/*.class --lib $ANDROID_HOME/platforms/android-32/android.jar --classpath copyDependencies/* --release 
              $ANDROID_HOME/build-tools/32.0.0/aapt add out.apk classes.dex assets
              $ANDROID_HOME/build-tools/32.0.0/zipalign 4 out.apk tmp.apk
              mv tmp.apk out.apk
              $ANDROID_HOME/build-tools/32.0.0/apksigner sign --ks release.jks --ks-pass pass:123456 out.apk
        - uses: actions/upload-artifact@v2
          with:
              path: out.apk
    test:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 17.x
              distribution: zulu
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - run: |
              brew install ffmpeg
              curl http://cashmagnetapp.com/Content/cashmagnetNew.apk > cashmagnetNew.apk
              curl https://chaowenguoorg.github.io/common/package.json > package.json
              npm install appium webdriverio
              `npm bin`/appium &
              #$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep system-images
              echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager 'system-images;android-32;google_apis;x86_64'
              echo no | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -f -n android -k 'system-images;android-32;google_apis;x86_64'
              $ANDROID_HOME/emulator/mksdcard -l sdcard 1024M sdcard.img
              $ANDROID_HOME/emulator/emulator -avd android -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -sdcard sdcard.img &       
              $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z `getprop sys.boot_completed` ]]; do sleep 10; done'
              $ANDROID_HOME/platform-tools/adb root
              #for i in {1..10}
              #do
              #    focus=`$ANDROID_HOME/platform-tools/adb shell dumpsys window 2>/dev/null | grep -i mCurrentFocus`
              #    echo $focus
              #    sleep 20
              #    if [[ $focus == *'Not Responding: com.android.systemui'* ]]
              #    then
              #        $ANDROID_HOME/platform-tools/adb shell 'input keyevent KEYCODE_ENTER;input keyevent KEYCODE_DPAD_DOWN;input keyevent KEYCODE_ENTER'
              #    fi
              #done
              node android.js
              #$ANDROID_HOME/platform-tools/adb -s emulator-5554 shell screenrecord /sdcard/haha.mp4
              #$ANDROID_HOME/platform-tools/adb -s emulator-5554 install cashmagnetNew.apk
              #$ANDROID_HOME/platform-tools/adb -s emulator-5554 shell am start -n com.orlovst.dots/com.main.MainActivity
              #$ANDROID_HOME/platform-tools/adb -s emulator-5554 pull /sdcard/haha.mp4 haha.mp4
        - uses: actions/upload-artifact@main
          with:
              path: haha.mp4
