on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 16.x
        - run: |
              keytool -genkey -keystore release.jks -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -alias release -dname "CN=(名字与姓氏), OU=(组织单位名称), O=(组织名称), L=(城市或区域名称), ST=(州或省份名称), C=(单位的两字母国家代码)"
              JAVA_HOME=/usr gradle build -Dorg.gradle.warning.mode=all
        - uses: actions/upload-artifact@v2
          with:
              path: android-release.apk
    test:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - uses: actions/setup-java@main
          with:
              java-version: 17.x
              distribution: zulu
        - run: |
              npm install appium webdriverio
              `npm bin`/appium &
              curl https://chaowenguoorg.github.io/common/package.json > package.json
              #$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep system-images
              yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-32;google_apis;x86_64'
              echo 'no' | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n android -k 'system-images;android-32;google_apis;x86_64'
              $ANDROID_HOME/emulator/emulator -avd android &
              $ANDROID_HOME/emulator/emulator -list-avds
              /usr/local/lib/android/sdk/platform-tools/adb devices
              node android.js
